using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;

namespace vivaprocess
{
    public partial class frmClients : Form
    {
        public frmClients()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource manager='" + lookUpManager.Properties.GetDataSourceValue("PERS_NAME", lookUpManager.ItemIndex).ToString().Trim() + "'
            sqlDataClients.Fill();
            sqlDataManager.Fill();
        }

[System.Diagnostics.CodeAnalysis.SuppressMessage("CodeRush", "String.Format can be used")]
        private void btnSaveClient_Click(object sender, EventArgs e)
        {
            int fClient = 0;
            string constr = "User Id=" + vivaprocess.Global.ora_user + "; Password=" + vivaprocess.Global.ora_pass + "; Data Source=" + vivaprocess.Global.ora_serv;
            OracleConnection con = new OracleConnection(constr);
            try
            {
                con.Open();
                OracleCommand cmd = con.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = "SELECT count(client_name) as num FROM clients where client_name='" + txtClient.Text.Trim() + "'";
                OracleDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    fClient = (int)reader.GetDecimal(0);
                }
            }
            catch (Exception ex)
            {
                DevExpress.XtraEditors.XtraMessageBox.Show(ex.Message);
            }
            finally
            {
                con.Dispose();
            }

            if (fClient == 0) { 
                if (txtClient.Text.Length>0)
                {
                    constr = "User Id=" + vivaprocess.Global.ora_user + "; Password=" + vivaprocess.Global.ora_pass + "; Data Source=" + vivaprocess.Global.ora_serv;
                    con = new OracleConnection(constr);
                    try
                    {
                        int fNum=1;
                        con.Open();
                        OracleCommand cmd = con.CreateCommand();
                        cmd.CommandType = CommandType.Text;
                        cmd.CommandText = "select nvl((SELECT max(client_id) as num FROM clients),0)+1 as num from dual";
                        OracleDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            fNum = (int)reader.GetDecimal(0);
                        }
                        cmd.CommandText = "insert into clients(client_id,client_name,client_tel,client_addr,client_descr,client_code,manager) values(" + fNum + ",'" + txtClient.Text.Trim() + "','" + txtTel.Text.Trim() + "','" + txtAdres.Text.Trim() + "','" + txtDescr.Text.Trim() + "','" + txtCode.Text.Trim() + "','" + lookUpManager.Properties.GetDataSourceValue("PERS_NAME", lookUpManager.ItemIndex).ToString().Trim() + "')";
                        cmd.ExecuteNonQuery();
                        //lblClientId.Text=fNum;
                    }
                    catch (Exception ex)
                    {
                        DevExpress.XtraEditors.XtraMessageBox.Show(ex.Message);
                    }
                    finally
                    {
                        con.Dispose();
                    }
                    sql_log("insert.");
                    this.sqlDataClients.Fill();
                    lookUpClients.EditValue = lookUpClients.Properties.GetKeyValueByDisplayText(txtClient.Text);
                    lblClientId.Text = lookUpClients.EditValue.ToString();
                }
                else
                {
                    DevExpress.XtraEditors.XtraMessageBox.Show("Заполните поля..", "Ошибка", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            else
            {
                DialogResult DelClient = DevExpress.XtraEditors.XtraMessageBox.Show("Такой клиент существует, обновить информацию ?", "Подтвержедние", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                if (DelClient == System.Windows.Forms.DialogResult.Yes)
                {
                    constr = "User Id=" + vivaprocess.Global.ora_user + "; Password=" + vivaprocess.Global.ora_pass + "; Data Source=" + vivaprocess.Global.ora_serv;
                    con = new OracleConnection(constr);
                    try
                    {
                        con.Open();
                        OracleCommand cmd = con.CreateCommand();
                        cmd.CommandText = "update clients set client_tel='" + txtTel.Text.Trim() + "', client_addr='" + txtAdres.Text.Trim() + "', client_descr='" + txtDescr.Text.Trim() + "', client_code='" + txtCode.Text.Trim() + "', manager='" + lookUpManager.Properties.GetDataSourceValue("PERS_NAME", lookUpManager.ItemIndex).ToString().Trim() + "' where client_name='" + txtClient.Text.Trim() + "'";
                        cmd.ExecuteNonQuery();
                    }
                    catch (Exception ex)
                    {
                        DevExpress.XtraEditors.XtraMessageBox.Show(ex.Message);
                    }
                    finally
                    {
                        con.Dispose();
                    }
                    sql_log("update.");
                    this.sqlDataClients.Fill();
                }
            }
        }

        private void frmClients_Load(object sender, EventArgs e)
        {
            lookUpClients.ItemIndex = 0;
        }

        private void lookUpClients_EditValueChanged(object sender, EventArgs e)
        {
            lblClientId.Text = lookUpClients.EditValue.ToString();
            txtClient.Text = lookUpClients.Properties.GetDataSourceValue("CLIENT_NAME", lookUpClients.ItemIndex).ToString().Trim();
            txtTel.Text = lookUpClients.Properties.GetDataSourceValue("CLIENT_TEL", lookUpClients.ItemIndex).ToString().Trim();
            txtAdres.Text = lookUpClients.Properties.GetDataSourceValue("CLIENT_ADDR", lookUpClients.ItemIndex).ToString().Trim();
            txtDescr.Text = lookUpClients.Properties.GetDataSourceValue("CLIENT_DESCR", lookUpClients.ItemIndex).ToString().Trim();
            txtCode.Text = lookUpClients.Properties.GetDataSourceValue("CLIENT_CODE", lookUpClients.ItemIndex).ToString().Trim();
            lookUpManager.EditValue = lookUpManager.Properties.GetKeyValueByDisplayText(lookUpClients.Properties.GetDataSourceValue("MANAGER", lookUpClients.ItemIndex).ToString().Trim());
        }

        private void btnDelClient_Click(object sender, EventArgs e)
        {
            DialogResult DelClient = DevExpress.XtraEditors.XtraMessageBox.Show("Вы уверены, что хотите удалить клиента ?", "Подтвержедние", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (DelClient==System.Windows.Forms.DialogResult.Yes)
            {
                string constr = "User Id=" + vivaprocess.Global.ora_user + "; Password=" + vivaprocess.Global.ora_pass + "; Data Source=" + vivaprocess.Global.ora_serv;
                OracleConnection con = new OracleConnection(constr);
                try
                {
                    con.Open();
                    OracleCommand cmd = con.CreateCommand();
                    cmd.CommandText = "delete clients where client_name='" + txtClient.Text.Trim() + "'";
                    cmd.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    DevExpress.XtraEditors.XtraMessageBox.Show(ex.Message);
                }
                finally
                {
                    con.Dispose();
                }
                sql_log("delete.");
                this.sqlDataClients.Fill();
                lookUpClients.ItemIndex = 0;
            }
        }

        private void sql_log(string log_msg)
        {
            log_msg += SystemInformation.ComputerName.ToString();
            log_msg += "." + vivaprocess.Global.user_this.ToString();
            string constr = "User Id=" + vivaprocess.Global.ora_user + "; Password=" + vivaprocess.Global.ora_pass + "; Data Source=" + vivaprocess.Global.ora_serv;
            OracleConnection con = new OracleConnection(constr);
            try
            {
                int fNum = 1;
                con.Open();
                OracleCommand cmd = con.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = "select nvl((SELECT max(id) as num FROM clients_log),0)+1 as num from dual";
                OracleDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    fNum = (int)reader.GetDecimal(0);
                }
                cmd.CommandText = "insert into clients_log(id,in_log) values(" + fNum + ",'" + log_msg + "')";
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                DevExpress.XtraEditors.XtraMessageBox.Show(ex.Message);
            }
            finally
            {
                con.Dispose();
            }
        }
    }
}
