using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using DevExpress.DataAccess.ConnectionParameters;
using DevExpress.DataAccess.Sql;
using DevExpress.XtraGrid.Views.Grid;

namespace vivaprocess
{
    public partial class frmKuhniSlegFull : Form
    {
        frmKuhniFull frmKuhniFullF;
        public frmKuhniSlegFull()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            refresh_kuhni();
        }

        private void frmKuhniSlegFull_Load(object sender, EventArgs e)
        {
            dateEnd.Text = DateTime.Now.ToString("dd.MM.yyyy");
            dateStart.Text = "01." + DateTime.Now.ToString("MM.yyyy");
            refresh_kuhni();
        }

        public void refresh_kuhni()
        {
            this.Cursor = System.Windows.Forms.Cursors.WaitCursor;

            OracleConnectionParameters connectionParameters = new OracleConnectionParameters(vivaprocess.Global.ora_serv, "kuhni_modul", "kuhni");
            SqlDataSource ds = new SqlDataSource(connectionParameters);
            // Create an SQL query to access the Products table. 
            CustomSqlQuery query = new CustomSqlQuery();
            query.Name = "customQuery1";
            if (chkInWork.Checked == true & chkGotov.Checked == false & chkOtgrugen.Checked == false)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where prod_date_otgruzka is null and prod_id in (select t.prod_id from disp_kuhni t where (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy')) and (vse=1 or vse=" + vivaprocess.Global.vse + ") and t.mat_descr<>'нет' and t.sklad_gotov_fakt is null)"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy')) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == true & chkGotov.Checked == true & chkOtgrugen.Checked == false)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where prod_date_otgruzka is null"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == true & chkGotov.Checked == true & chkOtgrugen.Checked == true)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == true & chkGotov.Checked == false & chkOtgrugen.Checked == true)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where (prod_date_otgruzka is not null or prod_id in (select t.prod_id from disp_kuhni t where (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy')) and t.mat_descr<>'нет' and t.sklad_gotov_fakt is null))"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == false & chkGotov.Checked == false & chkOtgrugen.Checked == true)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where prod_date_otgruzka is not null"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == false & chkGotov.Checked == true & chkOtgrugen.Checked == false)
            {
                query.Sql = "select distinct trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where (prod_date_otgruzka is null and prod_id not in (select t.prod_id from disp_kuhni t where (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy')) and t.mat_descr<>'нет' and t.sklad_gotov_fakt is null))"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else if (chkInWork.Checked == false & chkGotov.Checked == true & chkOtgrugen.Checked == true)
            {
                query.Sql = "select trunc(nvl(prod_id,0)) NN,prod_name NN_клиента,nvl(client_name,' ') клиент,nvl(prod_descr,' ') описание,nvl(to_char(prod_date_in,'dd.mm.yyyy'),' ') дата_поступл,"
                        + " nvl(to_char(prod_date_need,'dd.mm.yy'),' ') отгруз_план,nvl(to_char(date_tehnol,'dd.mm.yy'),' ') в_техотдел,"
                        + " nvl(tehnolog,' ') исполнитель,nvl(prod_cena,0) цена,"
                        + " nvl(to_char(prod_date_otgruzka,'dd.mm.yy'),' ') отгруз_факт,nvl(prod_descr_otgruzka,' ') примечания"
                        + " FROM disp_kuhni where (prod_date_otgruzka is not null or prod_id not in (select t.prod_id from disp_kuhni t where (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy')) and t.mat_descr<>'нет' and t.sklad_gotov_fakt is null))"
                        + " and (prod_date_in between to_date('" + dateStart.Text + "','dd.mm.yyyy') and to_date('" + dateEnd.Text + "','dd.mm.yyyy') and (vse=1 or vse=" + vivaprocess.Global.vse + ")) order by дата_поступл,NN";
            }
            else
            {
                this.Cursor = System.Windows.Forms.Cursors.Default;
                return;
            }
            ds.Queries.Add(query);
            ds.Fill();
            //Assign the data source for the grid and retrieve fields. 
            gridControl1.DataSource = ds;
            gridControl1.DataMember = "customQuery1";
            gridView1.Columns["NN"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            gridView1.Columns["NN"].DisplayFormat.FormatString = "n0";
            gridView1.Columns["ЦЕНА"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            gridView1.Columns["ЦЕНА"].DisplayFormat.FormatString = "n2";
            if (vivaprocess.Global.prava == "технолог" || vivaprocess.Global.prava == "цех" || vivaprocess.Global.prava == "склад продукции" || vivaprocess.Global.prava == "снабжение")
            {
                gridView1.Columns["ЦЕНА"].Visible=false;
            }
            gridView1.BestFitColumns();
            /*gridView1.Columns["ДАТА"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ДАТА"].DisplayFormat.FormatString = "dd.M.yyyy";
            gridView1.Columns["ОТГРУЗ_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ОТГРУЗ_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["В_ТЕХОТДЕЛ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["В_ТЕХОТДЕЛ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["ПРОИЗВ_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ПРОИЗВ_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["ПРОИЗВ_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ПРОИЗВ_ФАКТ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["КРАСКА_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["КРАСКА_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["КРАСКА_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["КРАСКА_ФАКТ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["ОТК_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ОТК_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["ОТК_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ОТК_ФАКТ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["СБОРКА_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["СБОРКА_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["СБОРКА_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["СБОРКА_ФАКТ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["СКЛ_ГОТ_ПЛАН"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["СКЛ_ГОТ_ПЛАН"].DisplayFormat.FormatString = "d";
            gridView1.Columns["СКЛ_ГОТ_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["СКЛ_ГОТ_ФАКТ"].DisplayFormat.FormatString = "d";
            gridView1.Columns["СНАБЖ_ЗАЯВКА"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["СНАБЖ_ЗАЯВКА"].DisplayFormat.FormatString = "d";
            gridView1.Columns["ОТГРУЗ_ФАКТ"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime;
            gridView1.Columns["ОТГРУЗ_ФАКТ"].DisplayFormat.FormatString = "d";*/
            this.Cursor = System.Windows.Forms.Cursors.Default;
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            this.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            vivaprocess.Global.slegFlag = 1;
            vivaprocess.Global.slegDate = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "ДАТА_ПОСТУПЛ").ToString();   //prod_date_in
            vivaprocess.Global.slegNN = Convert.ToInt32(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NN")).ToString();
            int newF = 1;
            foreach (Form frmKuhniFullFf in Application.OpenForms)
                if (frmKuhniFullFf is frmKuhniFull)
                {
                    frmKuhniFullFf.Activate();
                    newF = 0;
                    break;
                }
            if (newF == 1)
            {
                frmKuhniFullF = new frmKuhniFull();
                frmKuhniFullF.MdiParent = this.MdiParent;
                frmKuhniFullF.Show();
            }
            //lblTest.Text = Convert.ToInt32(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NN")).ToString();
            this.Cursor = System.Windows.Forms.Cursors.Default;
        }
    }
}
